# Generated by Django 3.1.7 on 2021-06-27 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210627_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='total_owed',
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_of_nights',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
