# Generated by Django 3.1.7 on 2021-06-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210627_0224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date_from']},
        ),
    ]
