# Generated by Django 3.1.7 on 2021-06-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210627_1348'),
        ('main_app', '0002_auto_20210627_0503'),
    ]

    operations = [
    ]
