# Generated by Django 3.1.7 on 2021-06-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_reservation_total_owed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='capacity',
            new_name='people_capacity',
        ),
        migrations.AddField(
            model_name='room',
            name='pets_capacity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
