# Generated by Django 3.1.7 on 2021-06-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210630_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='key',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
