# Generated by Django 3.1.7 on 2021-07-01 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210701_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_nights',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
