# Generated by Django 3.1.7 on 2021-07-02 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20210701_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_to',
            field=models.DateField(default=datetime.date(2021, 7, 3)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_nights',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_owed',
            field=models.IntegerField(blank=True),
        ),
    ]
