# Generated by Django 3.1.7 on 2021-07-03 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20210702_2356'),
        ('main_app', '0012_photo_key'),
    ]

    operations = [
    ]
