# Generated by Django 3.1.7 on 2021-07-03 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20210703_0045'),
        ('main_app', '0017_merge_20210703_0040'),
    ]

    operations = [
    ]
