# Generated by Django 3.1.7 on 2021-07-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20210703_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_to',
            field=models.DateField(),
        ),
    ]
