# Generated by Django 3.1.7 on 2021-07-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_auto_20210704_0007'),
        ('main_app', '0028_auto_20210704_2049'),
    ]

    operations = [
    ]
